# Common environment for services
x-common-env: &common-env
  tty: true
  stdin_open: true
  stop_grace_period: 1s

# Services
services:
  realsense: 
    build:
      context: .
      target: realsense  
      args:
        USER: realsense
        LIBREALSENSE_VERSION: 2.56.2
    <<: *common-env
    network_mode: host
    image: vision-tdk:realsense
    container_name: tdk-realsense
    volumes:
      - /dev:/dev
      - $PWD/../packages/realsense-pkg:/home/realsense/vision-ws/src/realsense-ros
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=42
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"
    command: bash
    #bash -ic "colcon build && ros2 launch realsense2_camera rs_launch.py"

  gui:
    build:
      context: .
      target: gui
      args:
        USER: gui
    <<: *common-env
    network_mode: host
    image: vision-tdk:gui
    container_name: tdk-gui
    volumes:
      # X11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/gui/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml address:=localhost port:=8765

  opencv:
    build:
      context: .
      target: opencv
      args:
        USER: opencv
    <<: *common-env
    network_mode: host
    image: vision-tdk:opencv
    container_name: tdk-opencv
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=42
    volumes:
        - $PWD/../packages/opencv-pkg:/home/opencv/vision-ws/src/opencv_ros
    command: bash
  